// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oipoihniimisvdzqvkem.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9pcG9paG5paW1pc3ZkenF2a2VtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwODE1OTAsImV4cCI6MjA3MTY1NzU5MH0.OiK_VUUi7rlGb-JoFkGH1mFBsgpJOTPoSvQsYuM6LSQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});